name: FreeCloudPanel Reminder

on:
  workflow_dispatch:
  schedule:
    # 每天 01:00 UTC（日本时间10:00）
    - cron: "0 1 * * *"

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Check if today is a reminder day
        run: |
          START_DATE="2026-05-09"

          TODAY=$(date -u +%F)

          START_SECONDS=$(date -d "$START_DATE" +%s)
          TODAY_SECONDS=$(date -d "$TODAY" +%s)

          DIFF_DAYS=$(( (TODAY_SECONDS - START_SECONDS) / 86400 ))

          echo "Today: $TODAY"
          echo "Start: $START_DATE"
          echo "Diff: $DIFF_DAYS"

          if [ "$DIFF_DAYS" -ge 0 ] && [ $((DIFF_DAYS % 30)) -eq 0 ]; then
            curl -s -X POST "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendMessage" \
              -d chat_id=${{ secrets.CHAT_ID }} \
              -d text="🔔 FreeCloudPanel提醒：你的账号rabbie.cn@gmail.com和qn322060@gmail.com于2026年5月注册的FreeCloudPanel需要续期了，请记得连续签到至少5天。（第 ${DIFF_DAYS} 天,第$((DIFF_DAYS / 30+1))次）"
          else
            echo "今天不是提醒日。"
          fi
